let STEP_CONSTANTS = {
    SAME_BEHAVIOR: 1,
    BEHAVIOR_NOT_FOUND: 2,
    STEP_SUCCESS: 3,
    STEP_INVALID: 4,
    SELECT_ABSTRACTION: 5,
};
STEP_CONSTANTS = Object.freeze(STEP_CONSTANTS);

export default STEP_CONSTANTS;
