let CDL_WORKER_PROTOCOL = {
    LOAD_FILE: 1,
    GET_METADATA: 2,
    GET_POSITION_DATA: 3,
    GET_VARIABLE_STACK: 4,
    STEP_INTO: 5,
    STEP_OUT: 6,
    STEP_OVER_FORWARD: 7,
    STEP_OVER_BACKWARD: 8,
    GO_TO_START: 9,
    GO_TO_END: 10,
};
CDL_WORKER_PROTOCOL = Object.freeze(CDL_WORKER_PROTOCOL);

export default CDL_WORKER_PROTOCOL;
